package com.anexon.ethio_cal

import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.graphics.Color
import android.widget.RemoteViews

/** Auto-generated by flutter_android_widgets. */
class MyHomeWidgetGlassyDarkProvider : AppWidgetProvider() {

    companion object {
        private const val PREFS_NAME = "FlutterSharedPreferences"
        private const val KEY_PREFIX = "flutter_android_widgets_"
        private const val STYLE_PREFIX = KEY_PREFIX + "style_MyHomeWidgetGlassyDarkProvider_"
        const val ACTION_REFRESH = "com.anexon.ethio_cal.MyHomeWidgetGlassyDarkProvider.ACTION_REFRESH"
    }

    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
        for (appWidgetId in appWidgetIds) {
            updateAppWidget(context, appWidgetManager, appWidgetId)
        }
    }

    override fun onReceive(context: Context, intent: Intent) {
        super.onReceive(context, intent)
        when (intent.action) {
            ACTION_REFRESH -> {
                val mgr = AppWidgetManager.getInstance(context)
                val ids = mgr.getAppWidgetIds(ComponentName(context, MyHomeWidgetGlassyDarkProvider::class.java))
                onUpdate(context, mgr, ids)
            }
        }
    }

    private fun updateAppWidget(context: Context, appWidgetManager: AppWidgetManager, appWidgetId: Int) {
        val prefs: SharedPreferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val views = RemoteViews(context.packageName, R.layout.widget_my_home_widget_glassy_dark_provider)
        val density = context.resources.displayMetrics.density

        views.setTextViewText(R.id.text_0, prefs.getString("flutter.${KEY_PREFIX}ethiopian_date", "") ?: "")
        views.setTextViewText(R.id.text_1, prefs.getString("flutter.${KEY_PREFIX}ethiopian_day", "") ?: "")

        try {
            prefs.getString("flutter.${STYLE_PREFIX}layout_0_backgroundColor", null)?.let {
                views.setInt(R.id.layout_0, "setBackgroundColor", Color.parseColor(it)) }
            prefs.getString("flutter.${STYLE_PREFIX}layout_0_padding", null)?.let {
                val px = (it.toFloat() * density).toInt()
                views.setViewPadding(R.id.layout_0, px, px, px, px) }
            prefs.getString("flutter.${STYLE_PREFIX}layout_0_gravity", null)?.let {
                views.setInt(R.id.layout_0, "setGravity", gravityOf(it)) }
        } catch (_: Exception) {}

        try {
            prefs.getString("flutter.${STYLE_PREFIX}text_0_backgroundColor", null)?.let {
                views.setInt(R.id.text_0, "setBackgroundColor", Color.parseColor(it)) }
            prefs.getString("flutter.${STYLE_PREFIX}text_0_textColor", null)?.let {
                views.setTextColor(R.id.text_0, Color.parseColor(it)) }
            prefs.getString("flutter.${STYLE_PREFIX}text_0_textSize", null)?.let {
                views.setFloat(R.id.text_0, "setTextSize", it.toFloat()) }
            prefs.getString("flutter.${STYLE_PREFIX}text_0_maxLines", null)?.let {
                views.setInt(R.id.text_0, "setMaxLines", it.toInt()) }
            prefs.getString("flutter.${STYLE_PREFIX}text_0_gravity", null)?.let {
                views.setInt(R.id.text_0, "setGravity", gravityOf(it)) }
        } catch (_: Exception) {}

        try {
            prefs.getString("flutter.${STYLE_PREFIX}text_1_backgroundColor", null)?.let {
                views.setInt(R.id.text_1, "setBackgroundColor", Color.parseColor(it)) }
            prefs.getString("flutter.${STYLE_PREFIX}text_1_textColor", null)?.let {
                views.setTextColor(R.id.text_1, Color.parseColor(it)) }
            prefs.getString("flutter.${STYLE_PREFIX}text_1_textSize", null)?.let {
                views.setFloat(R.id.text_1, "setTextSize", it.toFloat()) }
            prefs.getString("flutter.${STYLE_PREFIX}text_1_maxLines", null)?.let {
                views.setInt(R.id.text_1, "setMaxLines", it.toInt()) }
            prefs.getString("flutter.${STYLE_PREFIX}text_1_gravity", null)?.let {
                views.setInt(R.id.text_1, "setGravity", gravityOf(it)) }
        } catch (_: Exception) {}

        appWidgetManager.updateAppWidget(appWidgetId, views)
    }

    private fun gravityOf(s: String) = when (s) {
        "center" -> android.view.Gravity.CENTER
        "end"    -> android.view.Gravity.END
        "fill"   -> android.view.Gravity.FILL
        else     -> android.view.Gravity.START
    }
}
